### ISSUE TITLE
LLVM -SYCL-args-flattening pass not working

### ISSUE THREAD

**Issue by keryell** [triSYCL/triSYCL#126]
On code example https://github.com/keryell/triSYCL/blob/device/tests/device_compiler/single_task_vector_add_automatic_drt.cpp it looks like the kernel lambda is not flatten and thus the generated SPIR is incorrect.

**Comment by yu810226** [comment]
This problem is solved in llvm branch: https://github.com/yu810226/llvm/tree/linya/sycl/automatic-array-argument-flattening

**Comment by yu810226** [comment]
And please use the clang in this branch to compile: https://github.com/yu810226/clang/tree/linya/sycl/device-no-loop-idiom

**Comment by keryell** [comment]
Is there a way to have this pass working without inlining every thing?

**Comment by yu810226** [comment]
This pass is not related to inline. In this code example, the error is happened in pre_kernel_caller.ll file. Since argument promotion can only be done with GEP instructions that only used by loads. And if there are llvm.memcpy instruction, there will always a bitcast instruction before to cast the pointer, so force instantiate_kernel and functions called in the instantiate_kernel in per_kernel_caller.ll to skip loop idiom opt pass.

**Comment by keryell** [comment]
Problem solved.
