### ISSUE TITLE
triSYCL and FPGA

### ISSUE THREAD

**Issue by pkestene** [triSYCL/triSYCL#206]
hello @keryell 

this is a naive question: for someone who would like to try using SYCL on an FPGA target, at least reproduce the work you did last year (as mentionned in your SC2017 slides), would you recommend using as a platform e.g. the new xilinx alveo boards ? It is doable using remote resources (e.g. through nimbix cloud) or should I expect additional difficulties ? Alternatively would you recommend buying a devel board ? in that case which one ?
Thank you.

**Comment by MathiasMagnus** [comment]
How does the device compiler currently work? What is it used for?

**Comment by keryell** [comment]
@MathiasMagnus The device compiler is the compiler doing the slicing of the single-source SYCL program into a pure host code and a pure device code. It adds also some stubs and glue to stitch everything to the runtime.
Look for example at https://github.com/triSYCL/triSYCL/blob/master/doc/architecture.rst#device-side-compilation-flow

**Comment by keryell** [comment]
@pkestene After some discussion inside Xilinx, the way to go for official SDx OpenCL support is to use Alveo boards. I hope we will have in a few months a triSYCL experimental version for Alveo and some container you can use with a cloud provider.

**Comment by j-stephan** [comment]
Hi,

my group would like to use FPGAs in combination with SYCL in the near future. We would like to get a student to work on this for a thesis, but this would only work if triSYCL + FPGAs are somewhat usable. May I ask about the current status of triSYCL and Alveo boards? Is the workflow as shown in the device compiler README still accurate / usable?

**Comment by keryell** [comment]
@j-stephan Since the creation of this issue, Intel announced their own SYCL implementation https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedWithSYCLCompiler.md and they have started to upstream it into the official Clang/LLVM.

We are working with Intel @bader to fuse our 2 implementations somehow because it does not make sense to have 2 open-source implementations. Just 1 is hard enough. :-)
It is the same workflow as what is described on https://github.com/triSYCL/triSYCL/blob/master/doc/architecture.rst but with the Intel SYCL Clang/LLVM compiler + some tweaks in the SYCL runtime + retargeting some LLVM passes from triSYCL to generate some Xilinx-friendly SPIR-df instead of SPIR-V.
So you still need to use Xilinx `xocc` to generate the FPGA bitstream.
Up to now, it works, so it seems like quite a feasible approach.
It is on an internal branch for now, but we should open it soon, since it is not about hiding secret stuff but rather hiding wild experiments...
When do you need it?

**Comment by j-stephan** [comment]
Oh, good to know that you are cooperating with Intel on this matter. I agree, this seems like the most sensible open-source approach.

We would like to start in the first weeks of April 2019. In case the current version of the internal branch wouldn't be available, are the current toolchains in a usable state? I unsuccessfully tried with the `master` and `release_70` branches on Ubuntu 18.04 but still need to try them on Ubuntu 16.04.

**Comment by keryell** [comment]
I have never tried anything on CentOS, because everything is old there and you need to re-install everything. GCC 4.8.3 by default... :-(
triSYCL is about experimenting SYCL with the latest features of postmodern C++.
Early April looks fine for trying new compiler workflow.

**Comment by keryell** [comment]
We have been working recently on https://github.com/triSYCL/sycl
Since it is early April, perhaps you @j-stephan could give a try?

**Comment by j-stephan** [comment]
Great news, thanks! We are currently setting up the infrastructure and are finalising the thesis goals, so work should commence next week. You will likely here fro me again in the near future ;-)

**Comment by keryell** [comment]
@pkestene I think this efforts is now going on actively with https://github.com/triSYCL/sycl so I guess we can close this ticket.

**Comment by keryell** [comment]
> my group would like to use FPGAs in combination with SYCL in the near future. We would like to get a student to work on this for a thesis, but this would only work if triSYCL + FPGAs are somewhat usable.

@j-stephan we are always pleased to have good students working on these aspects at Xilinx... :-)
