### ISSUE TITLE
Building triSYCL without boost.Compute

### ISSUE THREAD

**Issue by Ruyk** [triSYCL/triSYCL#35]
I am trying to use travis to build the SYCL Khronos Parallel STL with triSYCL automatically on each commit. However, I cannot set up OpenCL on travis (or at least not easily), so I cannot use boost compute.
It seems that triSYCL should not require boost compute to work, however, when trying to build without it it fails, for example https://travis-ci.org/Ruyk/SyclParallelSTL/jobs/221413128

This seems to be caused by boost compute headers not if/def out in some headers, for example in CL/sycl/opencl_type.hpp  
Is still the case that triSYCL can be built without boost compute and without OpenCL? That would be great since it will simplify my travis integration...
Thanks!

**Comment by keryell** [comment]
Oops.
Sorry for this, @JoanThibault should have tested this.
Thank you for having found the culprit.
This should be fixed with https://github.com/triSYCL/triSYCL/commit/e4923d2735e005a639999bd1832294591145d001

@a-doumoulakis is also deploying Travis-CI on top of your configuration.
This uses docker to install a modern Linux image with OpenCL CPU support to run the OpenCL versions too.
We should share our infrastructure configuration.
@a-doumoulakis: be sure you test all the combinations with/without `BUILD_OPENCL` and `TRISYCL_OPENMP`

**Comment by Ruyk** [comment]
Thanks. That docker image would be great! I'll be looking forward for it @a-doumoulakis .
