### ISSUE TITLE
Doc needs massive overhaul/simplification

### ISSUE THREAD

**Issue by hughperkins** [triSYCL/triSYCL#50]
Should be possible to run just 2 or 3 commands to get as far as being able to run one of the test scripts.

Take a look at https://blog.cwrichardkim.com/how-to-get-hundreds-of-stars-on-your-github-project-345b065e20a2?gi=c037a694a63b

**Comment by hughperkins** [comment]
Concretely, some ideas:

1. Keep the front page clean, short__ those huge blocks of text on the front page, like 'presentations', 'possible futures' => move each to its individual page, and just provide a one-line link to it on the front page, maybe with a title:

### Presentations about triSYCL

- [Presentations about triSYCL](doc/presentations.md)

2. remove `mnag@matty` yada yada from the build commands:

```
$ cmake -DCMAKE_C_COMPILER=clang-4.0 -DCMAKE_CXX_COMPILER=clang++-4.0 -DTRISYCL_OPENMP=OFF ..
```

3. move `news` to the bottom of the front page

**Comment by hughperkins** [comment]
(Also, what is the reasoning behind using `.rst` rather than `.md`? I think `.md` is generally more standard,in github, though I know that http://pypi.python.org does use `.rst`s)

**Comment by hughperkins** [comment]
Preference to store the doxygen documentation in triSYCL.github.io, rather than xilinux.github.io

**Comment by hughperkins** [comment]
How I imagine the README: https://github.com/hughperkins/triSYCL/tree/simplify-readme

**Comment by hughperkins** [comment]
Oh man,n this page is a nightmare :-P https://github.com/hughperkins/triSYCL/blob/simplify-readme/tests/README.rst . Can we split this into:
- main page. simple. just a couple of commands to run
- link to an 'advanced' page or an 'options' page, handling cool advanced options, that we dont need to know, in order to simply run it the first time :-)

**Comment by hughperkins** [comment]
like:

To run triSYCL tests on your CPU, with no fancy bits, you can do simply:
```
mkdir build
cd build
cmake ..
make tests
make run-tests
```

__Advanced stuff :-):__

- To run on Xilinux FPGAs, please see ...
- To use OpenMP, pelase see...
- ...

**Comment by MathiasMagnus** [comment]
I do agree that the docs could be organized to have a few more leaf nodes and have a cleaner greeting page. The info currently there is very useful, but may not be of general interest. (Indeed, sometimes less is more.)

However, the cornerstone of triSYCL is OpenMP, so I would not consider opting out of it the 'default' mode, rather than people opting out if they have a compiler that does not support it.

You are right, that the leading info for every command-line invocation is also not of general interest, and thus should be removed. Do also take into consideration that that is a copy-paste of a pull request note and was never intended to be consumed by the masses. It just happened to be so close to actual documentation that it got dumped there. I believe it is still in far better shape than most docs in the wild.

If you wish to increase the quality of the docs, I suggest you create a PR and proceed by fixing requests. Ronan will not reject contributions that increase the quality of the product. My MSVC contributions were too not planned but were mainlined to increase the user base. Shiny docs could serve the same purpose.

**Comment by hughperkins** [comment]
https://github.com/triSYCL/triSYCL/pull/54

**Comment by keryell** [comment]
Yes the doc needs a lot of improvement. Some stuff should go to a Wikipedia page on SYCL too. :-)
I use ReST format because I have a strong background in Python/Zope/Plone for 2 decades and I find this format better designed than MarkDown.

**Comment by keryell** [comment]
I can cherry pick your commits and build the ReST front-end on this, so you do not have to dive into the `.rst`...

**Comment by hughperkins** [comment]
Cool, sounds good :-)

**Comment by hughperkins** [comment]
so, apparently, pytorch is using rsts too, https://github.com/pytorch/tutorials/blob/master/beginner_source/former_torchies_tutorial.rst , so seems like you are in good company there.

I think pytorch docs might be a bit less 'busy' though?  http://pytorch.org/tutorials/
