### ISSUE TITLE
Question: Architecture?

### ISSUE THREAD

**Issue by hughperkins** [triSYCL/triSYCL#51]
What is the architecture?

Concretely, if I wanted to get a sycl program converted into some kind of llvm bytecode-thing, but not yet converted into openmp/xilinx/etc, how would I do that?

**Comment by hughperkins** [comment]
Or, is it like, this is a pure C++ implementation, never goes via an intermediate llvm/spir layer, created in order to easily try out how to use sycl?  What options exist to write sycl code into some kind of llvm/spir thing?

**Comment by MathiasMagnus** [comment]
Yes. The implementation is ISO C++ with OpenMP (the latter can be opted out of using defines). You can extract any intermediate that your compiler of choice support for these technologies.

**Comment by hughperkins** [comment]
Cool. (though in my opinion, probably implementations, like OpenMP should be opt-in, rather than opt-out, but that's orthogonal to this issue).

=> closing.

**Comment by keryell** [comment]
What you are asking for is not open-sourced yet. :-(
I have an LLVM inSPIRation pass to transform the LLVM IR to SPIR 2.0 "de-facto", because based on a recent version of LLVM.
It would require some effort to generate official SPIR 1.2, because it is based on older LLVM 3.2 bitcode.
So even if I give you the source of this pass, it will not solve your issue. :-(
