### ISSUE TITLE
Kernels not running on GPU: cl::sycl::gpu_selector not work

### ISSUE THREAD

**Issue by babouFomb** [triSYCL/triSYCL#60]
Hi,

I successfully installed triSYCL on my PC with:
- a NVIDIA GeForce GT 745M GPU hoted in an Intel I5.
- Ubuntu 14.04.
- CUDA Driver / Runtime 8.0
- gcc / g++ 4.8 and 6.0
- Boost 1.63.0

All test programs (located in triSYCL/tests) compiled without any error and runtime error.

But when I did some examples and added try/catch with:
`queue myQueue([&](exception_list eL) {
      try {
        for (auto &e : eL) {
          std::rethrow_exception(e);
        }
      } catch (cl::sycl::exception e) {
        std::cout << " An exception has been thrown: " << e.what() << std::endl;
      }
    });` 
It compiled and linked successfully. But I got the following runtime error:

> Error: using a non implemented feature

Declaring a queue with `queue myQueue;` all things running fine but `myQueue.is_host()` return true, so kernel are running on host.

When I tried to use:
`cl::sycl::gpu_selector selector;
 cl::sycl::queue myQueue(selector)`

I got the same runtime error: 

> Error: using a non implemented feature

So I want to understand why my kernels are running on host instead of my GPU while I linked my programs with NVIDIA OpenCL implementation located in `/usr/local/cuda/`

Thanks.

**Comment by keryell** [comment]
Thank you for trying triSYCL!

As said in the README:

> This SYCL implementation is mainly based on C++1z (2017?) and OpenMP with execution on the CPU right now, but some parts of the non single-source OpenCL interoperability layer are implemented and the device compiler development is on-going for SPIR and SPIR-V.

Which means that the single-source mode is only supported for CPU. The OpenCL support is done for now only by providing explicit OpenCL kernels, SYCL being in that case a way to have OpenCL code but with super-easy host code managing the data transfers for you in a lazy way. There are some tests in `tests/kernel` and we use this mode to execute explicit OpenCL kernels in TensorFlow SYCL for example.

I have a device compiler prototype for single-source mode generating SPIR "de facto" (basically SPIR 2.0 in a LLVM 3.9.1 IR) that works with PoCL & Xilinx FPGA.
But since nVidia does not support SPIR yet I think, it would not work anyway with this compiler...

So if you have an nVidia GPU, the only wat is to use the GPU in OpenCL interoperability mode.

Are you compiling with `TRISYCL_OPENCL` defined by CMake or explicitly in the Makefile, at least?
If not, there is no OpenCL support at all...

Furthermore, the first

> Error: using a non implemented feature

you get is due to the fact that a `queue` with an error handler is not yet implemented. :-(

There are a lot of features not yet supported in triSYCL compared to ComputeCpp. But we are looking for some nice people to implement these features from the specification into this project... :-)

**Comment by keryell** [comment]
Now there is an implementation of SYCL for nVidia GPU: https://github.com/illuhad/hipSYCL

So closing this.

**Comment by keryell** [comment]
It seems also possible to use ComputeCpp with the CUDA backend of PoCL http://portablecl.org/cuda-backend.html
